import logging
from datetime import date, timedelta
from typing import List, Optional
from uuid import UUID
from langgraph.graph import StateGraph
from supabase import Client

from app.agents.companion import companion_agent
from app.agents.extractor import extractor_agent
from app.agents.scheduler import scheduler_agent
from app.agents.state import AlurChatState, AlurState
from app.agents.validate_ambiguity import validate_ambiguity_fn
from app.schemas.task import TaskResponse

logger = logging.getLogger(__name__)

# --- 1. Brain Dump Graph (Legacy / Direct) ---
_bd_workflow = StateGraph(AlurState)
_bd_workflow.add_node("extractor", extractor_agent)
_bd_workflow.add_node("validate_ambiguity", validate_ambiguity_fn)
_bd_workflow.add_node("scheduler", scheduler_agent)

_bd_workflow.add_edge("extractor", "validate_ambiguity")
_bd_workflow.add_edge("validate_ambiguity", "scheduler")

_bd_workflow.set_entry_point("extractor")
_bd_workflow.set_finish_point("scheduler")

brain_dump_graph = _bd_workflow.compile()


# --- 2. Chat Room Multi-Agent Graph ---
def route_by_type(state: AlurChatState) -> str:
    """Conditional edge routing based on Companion Agent classification."""
    msg_type = (state.get("message_type") or "CHAT").upper()
    if msg_type == "TASK_CAPTURE":
        return "task_capture"
    elif msg_type == "REFLECTION":
        return "reflection"
    elif msg_type == "CAPACITY_QUERY":
        return "capacity_query"
    return "chat"


def format_chat_response(state: AlurChatState) -> dict:
    """Format final AI response text if tasks were captured, or retain companion response."""
    msg_type = (state.get("message_type") or "CHAT").upper()
    scheduled = state.get("scheduled_tasks", [])

    if msg_type == "TASK_CAPTURE":
        if scheduled:
            task_titles = [f"• {t['title']} ({t.get('assigned_date', '')})" for t in scheduled]
            titles_str = "\n".join(task_titles)
            ai_response = (
                f"Saya telah mencatat dan menjadwalkan tugas berikut sesuai kapasitasmu:\n{titles_str}"
            )
        else:
            ai_response = "Tugas telah dicatat dan dimasukkan ke daftar To-do."
        return {"ai_response": ai_response}

    # For CHAT, REFLECTION, CAPACITY_QUERY, ai_response was already generated by companion_agent
    return {"ai_response": state.get("ai_response", "Pesan diterima.")}


_chat_workflow = StateGraph(AlurChatState)
_chat_workflow.add_node("companion", companion_agent)
_chat_workflow.add_node("extractor", extractor_agent)
_chat_workflow.add_node("validate_ambiguity", validate_ambiguity_fn)
_chat_workflow.add_node("scheduler", scheduler_agent)
_chat_workflow.add_node("respond", format_chat_response)

_chat_workflow.add_conditional_edges(
    "companion",
    route_by_type,
    {
        "task_capture": "extractor",
        "reflection": "respond",
        "chat": "respond",
        "capacity_query": "respond",
    },
)

_chat_workflow.add_edge("extractor", "validate_ambiguity")
_chat_workflow.add_edge("validate_ambiguity", "scheduler")
_chat_workflow.add_edge("scheduler", "respond")

_chat_workflow.set_entry_point("companion")
_chat_workflow.set_finish_point("respond")

chat_graph = _chat_workflow.compile()


# --- Execution Helpers ---
def run_brain_dump(text: str, user_id: UUID, supabase: Client) -> List[TaskResponse]:
    """Execute the end-to-end brain-dump orchestration pipeline and persist tasks in Supabase."""
    today = date.today()

    # 1. Fetch user daily capacity
    user_res = (
        supabase.table("users")
        .select("daily_capacity_hours, timezone")
        .eq("id", str(user_id))
        .execute()
    )

    daily_capacity_hours = 8.0
    if user_res.data:
        daily_capacity_hours = float(user_res.data[0].get("daily_capacity_hours") or 8.0)

    daily_capacity_minutes = int(daily_capacity_hours * 60)

    # 2. Fetch existing load for this week (from today to next 7 days)
    week_end = today + timedelta(days=7)
    existing_tasks_res = (
        supabase.table("tasks")
        .select("assigned_date, estimated_minutes")
        .eq("user_id", str(user_id))
        .gte("assigned_date", today.isoformat())
        .lte("assigned_date", week_end.isoformat())
        .neq("status", "DONE")
        .execute()
    )

    load_by_date: dict[str, int] = {}
    if existing_tasks_res.data:
        for t in existing_tasks_res.data:
            d_str = t["assigned_date"]
            mins = t.get("estimated_minutes") or 0
            load_by_date[d_str] = load_by_date.get(d_str, 0) + mins

    # 3. Invoke LangGraph
    initial_state: AlurState = {
        "raw_text": text,
        "user_id": str(user_id),
        "today_date": today.isoformat(),
        "daily_capacity_minutes": daily_capacity_minutes,
        "existing_load_minutes_by_date": load_by_date,
        "draft_tasks": [],
        "scheduled_tasks": [],
    }

    result = brain_dump_graph.invoke(initial_state)
    scheduled_tasks = result.get("scheduled_tasks", [])

    if not scheduled_tasks:
        return []

    # 4. Batch insert into Supabase tasks table
    insert_payload = []
    for st in scheduled_tasks:
        insert_payload.append({
            "id": st["id"],
            "user_id": str(user_id),
            "title": st["title"],
            "estimated_minutes": st.get("estimated_minutes"),
            "assigned_date": st["assigned_date"],
            "is_ambiguous": st.get("is_ambiguous", False),
            "recurrence_rule": st.get("recurrence_rule"),
            "recurrence_group_id": st.get("recurrence_group_id"),
            "source": "BRAIN_DUMP",
            "ai_generated": True,
            "status": "PENDING",
            "missed_follow_up": "NONE",
        })

    insert_res = supabase.table("tasks").insert(insert_payload).execute()
    if not insert_res.data:
        return []

    return [TaskResponse.model_validate(item) for item in insert_res.data]


def run_chat_message(message: str, user_id: UUID, supabase: Client) -> dict:
    """Execute full Chat Room multi-agent orchestration pipeline.

    - Classifies message intent via Companion Agent
    - Applies 2-Tone Persona (HONEST default, GENTLE on burnout/overload)
    - If TASK_CAPTURE: extracts and schedules tasks according to user capacity
    - Records conversation logs into Supabase conversation_logs
    """
    today = date.today()

    # 1. Fetch user capacity & preferences
    daily_capacity_hours = 8.0
    try:
        user_res = (
            supabase.table("users")
            .select("daily_capacity_hours, timezone")
            .eq("id", str(user_id))
            .execute()
        )
        if user_res.data:
            daily_capacity_hours = float(user_res.data[0].get("daily_capacity_hours") or 8.0)
    except Exception as e:
        logger.warning(f"Failed to fetch user capacity: {e}")

    daily_capacity_minutes = int(daily_capacity_hours * 60)

    # 2. Fetch conversation context (last 10 recent messages)
    conv_context = []
    try:
        logs_res = (
            supabase.table("conversation_logs")
            .select("role, content, message_type")
            .eq("user_id", str(user_id))
            .order("created_at", desc=True)
            .limit(10)
            .execute()
        )
        if logs_res.data:
            conv_context = list(reversed(logs_res.data))
    except Exception as e:
        logger.warning(f"Failed to fetch conversation context: {e}")

    # 3. Fetch task stats & existing load for this week
    load_by_date: dict[str, int] = {}
    completed_count = 0
    total_count = 0
    week_end = today + timedelta(days=7)

    try:
        existing_tasks_res = (
            supabase.table("tasks")
            .select("assigned_date, estimated_minutes, status")
            .eq("user_id", str(user_id))
            .gte("assigned_date", today.isoformat())
            .lte("assigned_date", week_end.isoformat())
            .execute()
        )
        if existing_tasks_res.data:
            for t in existing_tasks_res.data:
                total_count += 1
                if t.get("status") == "DONE":
                    completed_count += 1
                else:
                    d_str = t["assigned_date"]
                    mins = t.get("estimated_minutes") or 0
                    load_by_date[d_str] = load_by_date.get(d_str, 0) + mins
    except Exception as e:
        logger.warning(f"Failed to fetch existing tasks: {e}")

    completion_rate = (completed_count / total_count) if total_count > 0 else None

    # Fetch past 7 days missed tasks count
    seven_days_ago = today - timedelta(days=7)
    missed_count = 0
    try:
        missed_res = (
            supabase.table("tasks")
            .select("id")
            .eq("user_id", str(user_id))
            .eq("status", "MISSED")
            .gte("assigned_date", seven_days_ago.isoformat())
            .execute()
        )
        missed_count = len(missed_res.data or [])
    except Exception as e:
        logger.warning(f"Failed to fetch missed tasks: {e}")

    # Fetch recent AI reflection insights
    recent_insights = []
    try:
        insights_res = (
            supabase.table("ai_insights")
            .select("content")
            .eq("user_id", str(user_id))
            .order("created_at", desc=True)
            .limit(3)
            .execute()
        )
        recent_insights = [i["content"] for i in (insights_res.data or []) if i.get("content")]
    except Exception as e:
        logger.warning(f"Failed to fetch recent ai_insights: {e}")

    # 4. Invoke LangGraph chat machine
    initial_state: AlurChatState = {
        "raw_message": message,
        "user_id": str(user_id),
        "today_date": today.isoformat(),
        "daily_capacity_hours": daily_capacity_hours,
        "daily_capacity_minutes": daily_capacity_minutes,
        "existing_load_minutes_by_date": load_by_date,
        "recent_completion_rate": completion_rate,
        "consecutive_misses": missed_count,
        "recent_insights": recent_insights,
        "conversation_context": conv_context,
        "message_type": "CHAT",
        "tone_used": "HONEST",
        "draft_tasks": [],
        "scheduled_tasks": [],
        "ai_response": "",
    }
    # Set dynamic source for scheduler
    initial_state["source"] = "CHAT_ROOM"  # type: ignore

    result = chat_graph.invoke(initial_state)
    scheduled_tasks = result.get("scheduled_tasks", [])
    extracted_task_records: List[TaskResponse] = []

    # 5. Persist tasks if any
    if scheduled_tasks:
        insert_payload = []
        for st in scheduled_tasks:
            insert_payload.append({
                "id": st["id"],
                "user_id": str(user_id),
                "title": st["title"],
                "estimated_minutes": st.get("estimated_minutes"),
                "assigned_date": st["assigned_date"],
                "is_ambiguous": st.get("is_ambiguous", False),
                "recurrence_rule": st.get("recurrence_rule"),
                "recurrence_group_id": st.get("recurrence_group_id"),
                "source": "CHAT_ROOM",
                "ai_generated": True,
                "status": "PENDING",
                "missed_follow_up": "NONE",
            })
        try:
            ins_res = supabase.table("tasks").insert(insert_payload).execute()
            if ins_res.data:
                extracted_task_records = [TaskResponse.model_validate(item) for item in ins_res.data]
        except Exception as e:
            logger.error(f"Failed to insert chat-extracted tasks: {e}")

    # 6. Persist to conversation_logs
    try:
        task_ids = [st["id"] for st in scheduled_tasks]
        supabase.table("conversation_logs").insert([
            {
                "user_id": str(user_id),
                "role": "USER",
                "content": message,
                "message_type": result.get("message_type", "CHAT"),
                "session_date": today.isoformat(),
            },
            {
                "user_id": str(user_id),
                "role": "AI",
                "content": result.get("ai_response", ""),
                "message_type": result.get("message_type", "CHAT"),
                "extracted_task_ids": task_ids,
                "tone_used": result.get("tone_used", "HONEST"),
                "mood_detected": result.get("mood_detected"),
                "session_date": today.isoformat(),
            },
        ]).execute()
    except Exception as e:
        logger.error(f"Failed to persist conversation logs: {e}")

    return {
        "reply": result.get("ai_response", ""),
        "message_type": result.get("message_type", "CHAT"),
        "tone_used": result.get("tone_used", "HONEST"),
        "mood_detected": result.get("mood_detected"),
        "extracted_tasks": extracted_task_records,
    }
