"""Morning Brief API endpoint."""
from datetime import date
from typing import Any, Dict, Optional
from uuid import UUID
from fastapi import APIRouter, Depends, Query, status

from app.api.deps import get_current_user_id, get_morning_brief_service
from app.services.morning_brief_service import MorningBriefService

router = APIRouter(prefix="/morning-brief", tags=["morning-brief"])


@router.get("", status_code=status.HTTP_200_OK)
def get_morning_brief(
    target_date: Optional[date] = Query(None, alias="date", description="Target date (YYYY-MM-DD), defaults to today"),
    user_id: UUID = Depends(get_current_user_id),
    service: MorningBriefService = Depends(get_morning_brief_service),
) -> Dict[str, Any]:
    """Get morning brief for a specific date (defaults to today).

    If brief already exists, marks it as opened and returns cached content.
    If not yet generated by cron, generates on-demand with RAG grounding.
    """
    content, is_new = service.get_or_generate_brief_sync(user_id=user_id, brief_date=target_date)
    return {
        "status": "success",
        "data": content,
        "generated": is_new,
    }
